### ISSUE TITLE
用不起来

### ISSUE THREAD

**Issue by liijtedpibz0535** [KID-joker/proxy-web-storage#10]
stokado 1.1.1
vue 3.3.2

```
<script setup lang="ts">
import { local } from 'stokado'
local.test = 'hello stokado'
</script>
```

报错：
> Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'test')

原来的 proxy-web-storage 正常。

**Comment by KID-joker** [comment]
不好意思，前几个版本没注意package.json的配置，设置成了只允许browser引入。
1.1.2恢复cjs和mjs的引入了。
谢谢你的提醒！
