### ISSUE TITLE
Consider add indexdb support as a storage engine

### ISSUE THREAD

**Issue by owen800q** [KID-joker/proxy-web-storage#6]
Most browsers limit the default maximum storage size up to 5MB unless user relax the limit. 
indexedDB allows a larger store. It is nice if support indexedDB

**Comment by KID-joker** [comment]
hello, @owen800q . I am not familiar with indexedDB as it is rarely used. But I know there are already many repositories like localForage, PouchDB etc. What features do you want that they can't provide?

**Comment by KID-joker** [comment]
I haven't received your reply for a long time, so I'm closing this issue for now. If you have any other questions or suggestions, please open a new one.

**Comment by KID-joker** [comment]
@owen800q hello, you can try v3 in your project now. It can works with localForage to support indexedDB. Looking forward to more feedback from you.
