### ISSUE TITLE
有一个神奇的bug：使用session相关的方法getItem,setItem,key这些Storage原生的方法，都会作用到local上

### ISSUE THREAD

**Issue by MatrixAge** [KID-joker/proxy-web-storage#8]
`session.setItem('test',true)`事实上，设置进localStorage了。

暂时解决方案：folk了一份，把encode，decode方法导出去了，结合原生的`sessionStorage.setItem('test',encode(true))`来用。

**Comment by KID-joker** [comment]
我这边[测试](https://codesandbox.io/s/friendly-flower-lhi9v5?file=/src/index.js)没有复现，可以提供一个最小复现吗？

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/215238568-82cba27c-0dcf-40d0-87e2-55acaa1bfd98.png)

https://github.com/YaoApp/xgen/blob/main/packages/storex/__tests__/index.test.ts

可以试一下跑这个测试用例，把注释去掉是跑不通的。

**Comment by KID-joker** [comment]
1.0.7已修复

**Comment by MatrixAge** [comment]
thx
