### ISSUE TITLE
Console 里面总是输出'abc'

### ISSUE THREAD

**Issue by liijtedpibz0535** [KID-joker/proxy-web-storage#9]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/120783569/219306018-1bba4ef4-addf-4394-9d35-f450b1801354.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/120783569/219313288-fe1195c2-a0a4-4b16-8ed8-673a7db971e1.png">

**Comment by KID-joker** [comment]
感谢反馈，已经加上drop_console了。但是目前在重写测试用例，争取这周末更新上去。

**Comment by liijtedpibz0535** [comment]
这周末能更新吗？有项目等着发布😅

**Comment by KID-joker** [comment]
不好意思，上星期事情比较多，就没做完。我先更新下。

**Comment by KID-joker** [comment]
@liijtedpibz0535 已经更新1.0.8了，你试试

**Comment by liijtedpibz0535** [comment]
> @liijtedpibz0535 已经更新1.0.8了，你试试

更新了，OK了，感谢！
